# Generated by Django 3.1.4 on 2022-05-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_cart_commande_customer_example_order_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
